### ISSUE TITLE
Update release workflow to not use `set-output`

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/git-tag-annotation-action#359]
[The "Release" > "Create" workflow currently](https://github.com/ericcornelissen/git-tag-annotation-action/blob/07d57915adfae9f69f1f44689a50dc7ba06bd37d/.github/workflows/release.yml#L116-L125) uses `set-output` (as `echo "::set-output name=xxx::$yyy"`), which is an GitHub Actions' feature that [has been deprecated an may be disabled in the future](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

To ensure the automated releases keep working, the workflow should be updated to not use `set-output` (or `save-state`) anymore.

Based on https://github.com/github/codeql-action/compare/v2.1.27...v2.1.28 it looks like changing the workflow as follows _should_ work:

```diff
- echo "::set-output name=xxx::$yyy"
+ echo "xxx=$yyy" >> $GITHUB_OUTPUT
```

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by ericcornelissen** [comment]
Definitely @Vinitvh, I assigned you to it. Looking forward to your Pull Request 😄
