### ISSUE TITLE
Remove optional development dependency on Node.js

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/git-tag-annotation-action#511]
Relates to #436

## Summary

Currently this project has [an (optional) development prerequisite on Node.js](https://github.com/ericcornelissen/git-tag-annotation-action/blob/7e579b6d30006863205ca941cd9924c021097b62/CONTRIBUTING.md?plain=1#L102) due to the use of [JavaScript scripts](https://github.com/ericcornelissen/git-tag-annotation-action/tree/7e579b6d30006863205ca941cd9924c021097b62/script). This ticket exists to entertain the idea of removing this prerequisite - ideally without introducing a new prerequisite, or possibly with an alternative which may be more common or convenient.

**Comment by Karlitos88** [comment]
patch-1

**Comment by ericcornelissen** [comment]
@Karlitos88 please use English only when commenting on or working in this repository :slightly_smiling_face: 

From this translation of your comment:

> Well, we delete and we go to the next one to continue, I order to send the delete, then

if you have any suggestions for replacements of the scripts please feel free to share them here or submit a Pull Request.

**Comment by ericcornelissen** [comment]
I have some work going on in another project which could provide a replacement for the [`bump-version.mjs` script](https://github.com/ericcornelissen/git-tag-annotation-action/blob/7e579b6d30006863205ca941cd9924c021097b62/script/bump-version.mjs), see https://github.com/ericcornelissen/tool-versions-update-action/pull/147.
