### ISSUE TITLE
[Security] Workflow verify.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Freakston** [ericcornelissen/git-tag-annotation-action#61]
The workflow verify.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by ericcornelissen** [comment]
Thank you for informing me about this security fix @Freakston, I wasn't aware of it. However I'm not sure your report is entirely _correct_. Please let me know if my reasoning is incorrect :slightly_smiling_face: 

First, from what I can tell, [v1 of `actions/checkout`](https://github.com/actions/checkout/tree/releases/v1) isn't affected as it doesn't try to persist the credentials. Unfortunately the source code for v1 doesn't seem to be publicly available[^1] so it's a bit hard to verify.

Second, [the permissions for the token in question are limited to read-only](https://github.com/ericcornelissen/git-tag-annotation-action/blob/e82cc4d7cb0b247783422531807e1d347ee7b167/.github/workflows/verify.yml#L4) so obtaining a token doesn't gain you anything - everyone has read-only access to this project. (this was changed approximately three months ago, but logs for GitHub Actions on this repo are retained for less than that anyway).

As an aside, a more pressing issue would be that [the documentation for this action currently recommends using `actions/checkout@v1`](https://github.com/ericcornelissen/git-tag-annotation-action/tree/e82cc4d7cb0b247783422531807e1d347ee7b167#full-example) (see [the "Known Issues"](https://github.com/ericcornelissen/git-tag-annotation-action/blob/e82cc4d7cb0b247783422531807e1d347ee7b167/.github/workflows/verify.yml#L4) for an explanation as to why this is the case). So if `actions/checkout@v1` is actually vulnerable, updating that should probably have priority (especially given the limited permissions of the token in the "vulnerable" workflow of this repository).

[^1]: which might be reason enough to switch to v2 by itself but that's besides the point.
